apiVersion: apps/v1
kind: Deployment
metadata:
  name: minitwit
  labels:
    app: minitwit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minitwit
  template:
    metadata:
      labels:
        app: minitwit
    spec:
      containers:
        - name: minitwit
          image: michaelhaigh/minitwit:0.1.0
          ports:
            - containerPort: 5000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: db_root_password
            - name: db_name
              value: "minitwit"
            - name: db_host
              value: "mysql"
---
apiVersion: v1
kind: Service
metadata:
  name: minitwit
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: minitwit
  type: LoadBalancer
