version: "1.0"
stages:
  - clone
  - build
  - backup
  - deploy

steps:
  clone_repo:
    title: Cloning repository
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: github
    stage: clone
  build_push_image:
    title: Build and push Docker image
    type: build
    image_name: "michaelhaigh/minitwit" # Change michaelhaigh to your dockerhub username
    working_directory: "${{clone_repo}}"
    tag: "${{CF_SHORT_REVISION}}"
    dockerfile: Dockerfile
    registry: dockerhub
    stage: build
  astra_control_toolkit_backup:
      title: Astra Control Toolkit Create Backup
      type: netapp-tme/astra-control-toolkit
      stage: backup
      arguments:
        AC_CONFIG_SECRET: ac_config_yaml # Ensure this matches your shared secret
        ACTOOLKIT_VERSION: 2.6.7
        APP_ID: 52a2a242-cdb3-436b-966d-ba8c48e8e8df # Change to your Astra Control APP_ID
        COMMANDS:
          - actoolkit create backup $APP_ID cf-backup-$(date "+%Y%m%d%H%M%S")
  kubernetes_deploy:
    title: Deploy image to Kubernetes
    type: deploy
    stage: deploy
    kind: kubernetes
    cluster: gke_astracontroltoolkitdev_us-central1-b_gke-demo-cluster 
    namespace: minitwit
    service: minitwit
    candidate:
      image: michaelhaigh/minitwit:${{CF_SHORT_REVISION}} # Change michaelhaigh to your dockerhub username
      registry: dockerhub
